blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ ç¤¾åŒºæ”¯æŒ Support
    url: https://github.com/Tencent-TDS/KuiklyUI/discussions/categories/q-a
    about: ä¸€èˆ¬æ€§ã€å’¨è¯¢ç±»é—®é¢˜è®¨è®ºã€äº¤æµ
  - name: ğŸ—ï¸ ç”Ÿæ€å»ºè®¾ Ecosystem
    url: https://github.com/Tencent-TDS/KuiklyUI/discussions/categories/%E7%A4%BE%E5%8C%BA%E7%94%9F%E6%80%81
    about: ç»„ä»¶ã€é…å¥—å·¥å…·ç­‰äº’åŠ©è®¨è®ºã€åˆ†äº«